/**
 * Generate small WebP thumbnails for the home grid (max 480px).
 * Run: npm run thumbs
 * Reads project thumbnails from src/data/projects.ts, outputs to public/thumbs/*.webp.
 * HomeGrid will use these when available for faster first-page load.
 */

import { readFileSync, mkdirSync, writeFileSync, existsSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const publicDir = join(root, "public");
const thumbsDir = join(publicDir, "thumbs");

async function main() {
  let sharp: typeof import("sharp");
  try {
    sharp = (await import("sharp")).default;
  } catch {
    console.warn("Optional: install sharp for thumbnail generation: npm i -D sharp");
    writeManifest([]);
    process.exit(0);
    return;
  }

  const projectsPath = join(root, "src", "data", "projects.ts");
  const content = readFileSync(projectsPath, "utf-8");
  const thumbPaths = [...content.matchAll(/\bthumbnail:\s*["']([^"']+)["']/g)].map((m) => m[1]);
  const seen = new Set<string>();
  const generated: string[] = [];

  mkdirSync(thumbsDir, { recursive: true });

  for (const path of thumbPaths) {
    const name = path.replace(/^\//, "").replace(/\.[a-z]+$/i, "");
    if (seen.has(name)) continue;
    seen.add(name);
    const srcPath = join(publicDir, path.replace(/^\//, ""));
    if (!existsSync(srcPath)) {
      console.warn("Skip (not found):", srcPath);
      continue;
    }
    const outPath = join(thumbsDir, name + ".webp");
    try {
      await sharp(srcPath)
        .resize(480, 480, { fit: "inside", withoutEnlargement: true })
        .webp({ quality: 82 })
        .toFile(outPath);
      generated.push(name);
      console.log("Generated:", outPath);
    } catch (e) {
      console.warn("Failed", srcPath, e);
    }
  }

  writeManifest(generated);
  console.log("Thumbnails:", generated.length, "| manifest written.");
}

function writeManifest(names: string[]) {
  const out = join(root, "src", "data", "thumbManifest.ts");
  const content = `/** Generated by npm run thumbs – small grid thumbnails available. */\nexport const thumbManifest = new Set<string>(${JSON.stringify(names)});\n`;
  writeFileSync(out, content);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
