/**
 * Generated by scripts/prepare-pics-website.ts
 */

export interface PicsImage {
  src: string;
  width: number;
  height: number;
}

export interface PicsAlbum {
  id: string;
  title: string;
  images: PicsImage[];
}

export const picsAlbums: PicsAlbum[] = [
  {
    "id": "abstractlandschap",
    "title": "AbstractLandschap",
    "images": [
      {
        "src": "/pics-website/abstractlandschap/491608795_29656108060641110_876142772004010023_n-trim.webp",
        "width": 400,
        "height": 600
      },
      {
        "src": "/pics-website/abstractlandschap/491910447_29655445220707394_1003473685776074483_n-trim.webp",
        "width": 399,
        "height": 600
      },
      {
        "src": "/pics-website/abstractlandschap/IMG_6317-trim.webp",
        "width": 400,
        "height": 600
      },
      {
        "src": "/pics-website/abstractlandschap/VertiNieuw-trim.webp",
        "width": 453,
        "height": 600
      }
    ]
  },
  {
    "id": "albert-cuyp",
    "title": "Albert Cuyp",
    "images": [
      {
        "src": "/pics-website/albert-cuyp/IMG_4373-trim.webp",
        "width": 400,
        "height": 600
      },
      {
        "src": "/pics-website/albert-cuyp/IMG_4377-trim.webp",
        "width": 400,
        "height": 600
      },
      {
        "src": "/pics-website/albert-cuyp/IMG_4393-trim.webp",
        "width": 400,
        "height": 600
      },
      {
        "src": "/pics-website/albert-cuyp/IMG_4531-trim.webp",
        "width": 400,
        "height": 600
      },
      {
        "src": "/pics-website/albert-cuyp/IMG_4620-trim.webp",
        "width": 400,
        "height": 600
      }
    ]
  },
  {
    "id": "duinen",
    "title": "Duinen",
    "images": [
      {
        "src": "/pics-website/duinen/verti2-trim.webp",
        "width": 450,
        "height": 600
      },
      {
        "src": "/pics-website/duinen/492131814_29726935853558330_5950526167662999453_n-trim.webp",
        "width": 451,
        "height": 600
      }
    ]
  },
  {
    "id": "karakters",
    "title": "Karakters",
    "images": [
      {
        "src": "/pics-website/karakters/20230126-IMG_20230126_193718_2-trim.webp",
        "width": 450,
        "height": 600
      },
      {
        "src": "/pics-website/karakters/492501774_29753106314274617_4241858937304850357_n-trim.webp",
        "width": 400,
        "height": 600
      },
      {
        "src": "/pics-website/karakters/IMG_5944-trim.webp",
        "width": 400,
        "height": 600
      },
      {
        "src": "/pics-website/karakters/Screenshot 2026-03-04 172931-trim.webp",
        "width": 399,
        "height": 600
      }
    ]
  },
  {
    "id": "west",
    "title": "West",
    "images": [
      {
        "src": "/pics-website/west/493968796_29760636870188228_4982174522030733050_n-trim.webp",
        "width": 400,
        "height": 600
      },
      {
        "src": "/pics-website/west/492568225_29760637020188213_8061537354184738891_n-trim.webp",
        "width": 401,
        "height": 600
      },
      {
        "src": "/pics-website/west/493650898_29760637016854880_7467848534040929343_n-trim.webp",
        "width": 401,
        "height": 600
      }
    ]
  }
] as const;
